version: '3.8'

services:
  fastapi:
    build:
      context: ./app
    container_name: fastapi_container
    ports:
      - "8000:8000"

  streamlit:
    build:
      context: ./streamlit
    container_name: streamlit_container
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
